# Generated by Django 5.1.2 on 2025-09-02 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='deploymentlog',
            new_name='deployer_lo_deploym_661822_idx',
            old_name='deployer_lo_deploym_07e74e_idx',
        ),
    ]
