# Generated by Django 5.1.2 on 2025-09-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_deployer_lo_deploym_07e74e_idx_deployer_lo_deploym_661822_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deploy_key',
            field=models.TextField(blank=True, null=True, default='', help_text='SSH key for private repositories'),
        ),
    ]